@echo off
setlocal enabledelayedexpansion

:: ============================================
:: Auto-generate portfolio-data.js from image directories
:: Run this script whenever you add or remove photos
:: Usage: Double-click or run generate-portfolio-data.bat
::        Use --silent flag to skip pause (for automation)
:: ============================================

:: Check for --silent flag
set SILENT=0
if "%~1"=="--silent" set SILENT=1

if %SILENT%==0 (
    echo.
    echo ========================================
    echo   Portfolio Data Generator for Windows
    echo ========================================
    echo.
)

cd /d "%~dp0"

set OUTPUT_FILE=js\portfolio-data.js

if %SILENT%==0 echo Creating %OUTPUT_FILE%...
if %SILENT%==0 echo.

:: Start the JS file
(
echo /**
echo  * Portfolio Data Configuration
echo  * Auto-generated by generate-portfolio-data.bat
echo  * DO NOT EDIT MANUALLY - Run generate-portfolio-data.bat to regenerate
echo  */
echo.
echo const portfolioData = {
) > "%OUTPUT_FILE%"

:: Process each category
call :ProcessCategory editorial
call :ProcessCategory fashion
call :ProcessCategory beauty
call :ProcessCategory glam
call :ProcessCategory campaign
call :ProcessCategory bridal

:: Close the object and add export
(
echo };
echo.
echo // Export for module systems
echo if ^(typeof module !== 'undefined' ^&^& module.exports^) {
echo     module.exports = portfolioData;
echo }
) >> "%OUTPUT_FILE%"

if %SILENT%==0 (
    echo.
    echo ========================================
    echo   DONE! Generated %OUTPUT_FILE%
    echo ========================================
    echo.
    echo Press any key to exit...
    pause > nul
)
exit /b 0

:: ============================================
:: Function to process a single category
:: ============================================
:ProcessCategory
set CATEGORY=%1
set DIR=images\%CATEGORY%
set COUNT=0

echo   Processing %CATEGORY%...

:: Add category header
(
echo.
echo     // %CATEGORY% Category
echo     %CATEGORY%: [
) >> "%OUTPUT_FILE%"

:: Check if directory exists
if exist "%DIR%" (
    :: Process all image files (sorted alphabetically)
    :: Note: Windows dir is case-insensitive, so *.jpg matches *.JPG too
    for /f "tokens=*" %%f in ('dir /b /a-d /on "%DIR%\*.jpg" "%DIR%\*.jpeg" "%DIR%\*.png" "%DIR%\*.webp" 2^>nul') do (
        set FILENAME=%%f
        set ID=%CATEGORY:~0,2%-!COUNT!
        set PATH_STR=images/%CATEGORY%/!FILENAME!

        :: Add entry to file
        echo         { id: '!ID!', src: '!PATH_STR!', thumb: '!PATH_STR!', alt: '%CATEGORY%', category: '%CATEGORY%' },>> "%OUTPUT_FILE%"

        set /a COUNT+=1
    )
)

:: Close category array
echo     ],>> "%OUTPUT_FILE%"

echo     Found !COUNT! images in %CATEGORY%

exit /b 0
